services:
  db:
    image: postgres:16
    container_name: bronzedraw-db
    environment:
      POSTGRES_USER: bronzedraw
      POSTGRES_PASSWORD: bronzedraw_dev_password
      POSTGRES_DB: bronzedraw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bronzedraw-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bronzedraw"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
      - DEBUG=true
      - DATABASE_URL=postgresql://bronzedraw:bronzedraw_dev_password@db:5432/bronzedraw
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bronzedraw-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - bronzedraw-network

volumes:
  postgres_data:

networks:
  bronzedraw-network:
    driver: bridge
